---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/managed-by: quarkus
    app.kubernetes.io/name: debezium-crypto-app
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: debezium-crypto-app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: debezium-crypto-app-view
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: view
subjects:
  - kind: ServiceAccount
    name: debezium-crypto-app
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: debezium-crypto-app
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: debezium-crypto-app
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 4563
  selector:
    app.kubernetes.io/name: debezium-crypto-app
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: crypto-map
data:
  update.period: '2s'
  quarkus.http.port: '4563'
  quarkus.tls.trust-all: 'true'
  quarkus.hibernate-orm.database.generation: 'drop-and-create'
  quarkus.datasource.jdbc.url: 'jdbc:postgresql://postgresql:5432/coincap'
  quarkus.datasource.username: 'postgres'
  quarkus.datasource.password: 'postgres'
  quarkus.datasource.db-kind: 'postgresql'
  quarkus.kubernetes-config.enabled: 'true'
  quarkus.kubernetes-config.config-maps: 'crypto-map'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/managed-by: quarkus
    app.kubernetes.io/name: debezium-crypto-app
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: debezium-crypto-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: debezium-crypto-app
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
  template:
    metadata:
      annotations:
        app.quarkus.io/commit-id: 61e1879953817bab6c8c2e5a21b98653d9228b0e
        app.quarkus.io/build-timestamp: 2024-06-06 - 15:17:16 +0000
      labels:
        app.kubernetes.io/managed-by: quarkus
        app.kubernetes.io/name: debezium-crypto-app
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: quay.io/obabec/debezium-crypto-app:0.0.1
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 4563
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          name: debezium-crypto-app
          envFrom:
            - configMapRef:
                name: crypto-map
                optional: false
          ports:
            - containerPort: 4563
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/ready
              port: 4563
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          startupProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/started
              port: 4563
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
      serviceAccountName: debezium-crypto-app
