---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: prometheus-source
spec:
  instanceSelector:
    matchLabels:
      dashboards: "debezium"
  datasource:
    name: prometheus-server
    type: prometheus
    access: proxy
    url: http://prometheus-service.devconf.svc.cluster.local:80
    basicAuth: false
    basicAuthUser: internal
    isDefault: false
    version: 1
    editable: true
