{
 "title": "Debezium Server Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total number of events",
   "type": "graph",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "debezium_metrics_TotalNumberOfEventsSeen{context=~\"(binlog|streaming)\"}"
    }
   ]
  },
  { "title": "Streaming", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Time since last event",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "topk(1, debezium_metrics_MilliSecondsSinceLastEvent{context=~\"(binlog|streaming)\"})"
    }
   ]
  },
  {
   "title": "Event count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 20, "x": 3, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "debezium_metrics_TotalNumberOfEventsSeen{context=~\"(binlog|streaming)\"}",
     "legendFormat": "Total events received"
    },
    {
     "expr": "debezium_metrics_NumberOfSkippedEvents{context=~\"(binlog|streaming)\"}",
     "legendFormat": "Events skipped"
    }
   ]
  },
  {
   "title": "Connected",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_Connected{plugin=\"postgres\"}"
    }
   ]
  },
  {
   "title": "Remaining queue capacity",
   "type": "graph",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "debezium_metrics_QueueRemainingCapacity{}",
     "legendFormat": "Remaining queue capacity"
    }
   ]
  },
  {
   "title": "Snapshot",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Table count",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "debezium_metrics_TotalTableCount{}",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Remaining tables",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 3, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "debezium_metrics_RemainingTableCount{context=\"snapshot\"}",
       "legendFormat": "Remaining"
      }
     ]
    },
    {
     "title": "Running snapshot",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 6, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "debezium_metrics_SnapshotRunning{context=\"snapshot\"}"
      }
     ]
    },
    {
     "title": "Completed",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 9, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "debezium_metrics_SnapshotCompleted{context=\"snapshot\"}"
      }
     ]
    },
    {
     "title": "Aborted",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "debezium_metrics_SnapshotAborted{context=\"snapshot\"}"
      }
     ]
    },
    {
     "title": "Event count",
     "type": "graph",
     "gridPos": { "h": 9, "w": 23, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "debezium_metrics_TotalNumberOfEventsSeen{context=\"snapshot\"}",
       "legendFormat": "Total events received"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heap Memory",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{area=\"heap\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_memory_max_bytes{area=\"heap\"}",
       "legendFormat": "Maximum"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "jvm_threads_current{}", "legendFormat": "Running" },
      { "expr": "jvm_threads_peak{}", "legendFormat": "Maximum" },
      { "expr": "jvm_threads_started_total{}", "legendFormat": "Started in total" }
     ]
    }
   ]
  }
 ]
}